name = "GlobtimPlots"
uuid = "12345678-1234-1234-1234-123456789abc"
authors = ["Global Optimization Team"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[extensions]
GlobtimCairoMakieExt = "CairoMakie"
GlobtimGLMakieExt = "GLMakie"
GlobtimAnalysisExt = "DataFrames"
GlobtimVisualizationFrameworkExt = "PlotlyJS"
GlobtimDataExt = "CSV"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0" 
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[compat]
julia = "1.9"
GLMakie = "0.8, 0.9, 0.10"
CairoMakie = "0.10, 0.11, 0.12"
DataFrames = "1.6"
