name = "GlobtimPlots"
uuid = "12345678-1234-1234-1234-123456789abc"
authors = ["Global Optimization Team"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"

[extensions]
GlobtimCairoMakieExt = "CairoMakie"
GlobtimGLMakieExt = "GLMakie"
# GlobtimAnalysisExt = "DataFrames"  # Temporarily disabled - needs Optim dependency
GlobtimVisualizationFrameworkExt = "PlotlyJS"
GlobtimDataExt = "CSV"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[compat]
julia = "1.9"
GLMakie = "0.8, 0.9, 0.10"
CairoMakie = "0.10, 0.11, 0.12"
DataFrames = "1.6"
