name = "GlobtimPlots"
uuid = "dce1bbde-eed0-4d20-b978-1e0da4aec0e5"
version = "0.1.0"
authors = ["Global Optimization Team"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

# Tree visualization
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"

[weakdeps]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Tidier = "f0413319-3358-4bb0-8e7c-0c83523a93bd"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[extensions]
GlobtimCairoMakieExt = "CairoMakie"
GlobtimDataExt = "CSV"
GlobtimGLMakieExt = ["GLMakie", "DynamicPolynomials"]
GlobtimVisualizationFrameworkExt = "PlotlyJS"

[compat]
CSV = "0.10.15"
CairoMakie = "0.10, 0.11, 0.12, 0.13, 0.14, 0.15"
DataFrames = "1.6"
GLMakie = "0.8, 0.9, 0.10, 0.11, 0.12, 0.13"
JSON3 = "1.14.3"
Reexport = "1.2.2"
julia = "1.9"
